# Common configuration for PX4 autopilot
#
# Common configuration for PX4 autopilot
#
# /**:
#   ros__parameters:
#     startup_px4_usb_quirk: false

# # sys_status & sys_time connection options
# /**/conn:
#     ros__parameters:
#       heartbeat_rate: 1.0    # send heartbeat rate in Hertz
#       timeout: 10.0          # heartbeat timeout in seconds
#       timesync_rate: 10.0    # TIMESYNC rate in Hertz (feature disabled if 0.0)
#       system_time_rate: 1.0  # send system time to FCU rate in Hertz (disabled if 0.0)

# # sys_status
# /**/sys:
#   ros__parameters:
#     min_voltage: [10.0]   # diagnostics min voltage, use a vector i.e. [16.2, 16.0] for multiple batteries, up-to 10 are supported to achieve the same on a ROS launch file do: <rosparam param="sys/min_voltage">[16.2, 16.0]</rosparam>
#     disable_diag: false # disable all sys_status diagnostics, except heartbeat

# # sys_time
# /**/time:
#   ros__parameters:
#     time_ref_source: fcu  # time_reference source
#     timesync_mode: MAVLINK
#     timesync_avg_alpha: 0.6 # timesync averaging factor
    
# gps_input
/**/gps_input:
  ros__parameters:
    gps_rate: 10.0           # GPS data publishing rate


# vim:set ts=2 sw=2 et:
